#!/bin/sh
sudo apt-get install rofi
sudo apt-get install vim
sudo apt-get install git
sudo apt-get install feh
sudo apt-get install terminator
sudo apt-get install compton
sudo apt-get install scrot
sudo apt-get install openjdk-8-jdk
sudo apt-get install maven
sudo apt-get install xclip
sudo apt-get install curl
sudo apt-get install arandr
sudo apt-get install htop
sudo apt-get install thunar

sudo snap install spotify
